Update promptCMD so incorrect user syntax does not hid username
quackduck/devzat pull request #207
Opened 2023-08-17 02:00 UTC by CaenJones

When I attempted to use "prompt" in the past, it hid my username so I could only see it after I sent a message.

2023-08-18 12:04 UTC, CaenJones commented
YEAH!

2023-08-18 17:50 UTC, quackduck commented
Afaict, the change here is that empty prompts aren’t allowed and print an error message. I think empty prompts should be allowed but we can have devbot DM something like “(Your prompt is now empty. Did you mean to get more info about your prompt? Run `man prompt` for more info)”. Also we don’t really need a whole new setPrompt function: just change the original one to print a message! We dont need the errors package either :)

2023-08-19 09:32 UTC, quackduck requested changes

2023-08-19 09:32 UTC, quackduck commented on commands.go
> +        fmt.Println("(Your prompt is now empty. Did you mean to get more info about your prompt? Run man prompt for more info)")
You want to write to the user, not stdout!

2023-08-19 09:32 UTC, quackduck commented on commands.go
> +    } else {
I don't think we need a success message

2023-08-21 20:34 UTC, quackduck commented on commands.go
> +    }
```suggestion
	u.Prompt = line
	u.formatPrompt()
	if line == "" {
		u.writeln(Devbot, "(Your prompt is now empty. Did you mean to get more info about your prompt? Run `man prompt` for more info)")
	}
```

2023-08-21 20:35 UTC, quackduck approved these changes

2023-08-21 20:35 UTC, merged